- platform: template
  switches:
    watch_shield_tv:
      friendly_name: Watch Shield TV
      value_template: "{{ is_state_attr('remote.harmony_hub', 'current_activity', 'Shield TV') }}"
      turn_on:
        service: remote.turn_on
        data:
          entity_id: remote.harmony_hub
          activity: 'Shield TV'
      turn_off:
        service: remote.turn_off
        data:
          entity_id: remote.harmony_hub
          activity: 'PowerOff'
- platform: template
  switches:
    play_xbox_one:
      friendly_name: Play Xbox One
      value_template: "{{ is_state_attr('remote.harmony_hub', 'current_activity', 'Play Xbox One') }}"
      turn_on:
        service: remote.turn_on
        data:
          entity_id: remote.harmony_hub
          activity: 'Play Xbox One'
      turn_off:
        service: remote.turn_off
        data:
          entity_id: remote.harmony_hub
          activity: 'PowerOff'
- platform: template
  switches:
    play_nintendo_switch:
      friendly_name: Play Nintendo Switch
      value_template: "{{ is_state_attr('remote.harmony_hub', 'current_activity', 'Play Xbox One') }}"
      turn_on:
        service: remote.turn_on
        data:
          entity_id: remote.harmony_hub
          activity: 'Play Xbox One'
      turn_off:
        service: remote.turn_off
        data:
          entity_id: remote.harmony_hub
          activity: 'PowerOff'